### ISSUE TITLE
Pruebas Unitarias para la Visualización de Datos

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#20]
### Tareas: 
- Escribir pruebas para los gráficos de líneas, barras y comparativos.
- Validar los resultados de las pruebas y corregir errores

**Comment by samuelbonillaf** [comment]
Estos funcionan bien, el unico problema menor es que alguno de los datos es sobre un unico parametro lla grafica se ve horrible

**Comment by samuelbonillaf** [comment]
Hay graficos que dan error, son demasiado grandes para que el streamlit (gratis) los muestre
MessageSizeError: Data of size 232.7 MB exceeds the message size limit of 200.0 MB.

This is often caused by a large chart or dataframe. Please decrease the amount of data sent to the browser, or increase the limit by setting the config option server.maxMessageSize. [Click here to learn more about config options](https://docs.streamlit.io/develop/api-reference/configuration/config.toml).

Note that increasing the limit may lead to long loading times and large memory consumption of the client's browser and the Streamlit server.
Prueba con Admitidos : 2020-2022 : Seccional o principal : Principal
